# Setup
url: http://www.laurabethlong.com/tttt
baseurl: http://www.laurabethlong.com/tttt/


# Permalinks
permalink: pretty
relative_permalinks: true

# Pagination
paginate: 1
paginate_path: "/blog/:num/"
