# Setup
title: Laura Beth Long
description: I’m passionate about the conservative movement, digital influencing, and the intersection of the two.
url: http://www.laurabethlong.com/tttt
baseurl: http://www.laurabethlong.com/tttt


# Permalinks
permalink: pretty
relative_permalinks: true

# Pagination
paginate: 1
paginate_path: "blog/page/:num/"
